name: Release

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 14.x

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get package name
        run: echo "PACKAGE_NAME=$(jq .name package.json | tr -d '"')" >> $GITHUB_ENV
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: node
          package-name: ${{ env.PACKAGE_NAME }}
          bump-minor-pre-major: Yes
      - uses: actions/checkout@v2
        # These if statements ensure that a publication only occurs when a new release is created
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOT_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
